name: NavigationAdvancedSample

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/NavigationAdvancedSample.yaml'
      - 'NavigationAdvancedSample/**'
  pull_request:
    paths:
      - '.github/workflows/NavigationAdvancedSample.yaml'
      - 'NavigationAdvancedSample/**'

env:
  SAMPLE_PATH: NavigationAdvancedSample

jobs:
  build_and_test:
    runs-on: macOS-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties        

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Generate cache key
        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: navadv-${{ hashFiles('checksum.txt') }}

      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew assembleDebug lintDebug --stacktrace

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step
        with:
          api-level: 26
          arch: x86
          profile: Nexus 6
          disable-animations: true
          working-directory: ${{ env.SAMPLE_PATH }}
          script: |
            adb logcat -c
            adb logcat &
            ./gradlew :presentation:connectedDebugAndroidTest

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs-NavigationAdvancedSample
          path: ${{ env.SAMPLE_PATH }}/app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports-NavigationAdvancedSample
          path: ${{ env.SAMPLE_PATH }}/app/build/reports
